"""
Step 7 - Report average results per subject

Inputs:
    - evaluation_summary_llama.csv
      (generated by Step 6, with columns:
         Question, n_total, n_used, accuracy, qwk)

Task:
    - Exclude Q10.
    - For each subject:
        Science: Q1, Q2
        English: Q3, Q4, Q7, Q8, Q9
        Biology: Q5, Q6
      compute average accuracy and average QWK.
    - Print results and save to:
        evaluation_by_subject_llama.csv
"""

from pathlib import Path
import numpy as np
import pandas as pd

SUMMARY_PATH = Path("evaluation_summary_llama.csv")
SUBJECT_SUMMARY_PATH = Path("evaluation_by_subject_llama.csv")


def main():
    if not SUMMARY_PATH.exists():
        raise FileNotFoundError(f"Missing {SUMMARY_PATH}. Run Step 6 first.")

    df = pd.read_csv(SUMMARY_PATH)

    # Normalize Question labels to strings like "Q1", "Q2", etc.
    df["Question"] = df["Question"].astype(str).str.strip()

    # Exclude Q10
    df = df[df["Question"] != "Q10"].copy()

    # Subject mapping
    subject_map = {
        "Science": ["Q1", "Q2"],
        "English": ["Q3", "Q4", "Q7", "Q8", "Q9"],
        "Biology": ["Q5", "Q6"],
    }

    rows = []

    print("=== Average results by subject (excluding Q10) ===")
    for subject, questions in subject_map.items():
        sub_df = df[df["Question"].isin(questions)]

        if sub_df.empty:
            avg_acc = np.nan
            avg_qwk = np.nan
        else:
            avg_acc = sub_df["accuracy"].mean(skipna=True)
            avg_qwk = sub_df["qwk"].mean(skipna=True)

        rows.append(
            {
                "subject": subject,
                "questions": ", ".join(questions),
                "avg_accuracy": avg_acc,
                "avg_qwk": avg_qwk,
            }
        )

        acc_str = "NaN" if np.isnan(avg_acc) else f"{avg_acc:.4f}"
        qwk_str = "NaN" if np.isnan(avg_qwk) else f"{avg_qwk:.4f}"
        print(f"{subject:8s} | Questions: {', '.join(questions):15s} "
              f"| avg_accuracy = {acc_str} | avg_qwk = {qwk_str}")

    # Save subject-level summary
    df_subject = pd.DataFrame(rows)
    df_subject.to_csv(SUBJECT_SUMMARY_PATH, index=False)

    print(f"\nSubject-level summary written to {SUBJECT_SUMMARY_PATH.resolve()}")


if __name__ == "__main__":
    main()